### ISSUE TITLE
Panic when boulder is pushed into fire

### ISSUE THREAD

**Issue by quininer** [ozkriff/zemeroth#232]
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::panicking::panic
             at libcore/panicking.rs:51
   9: <core::option::Option<T>>::unwrap
             at /checkout/src/libcore/macros.rs:20
  10: <rancor::ComponentContainer<Id, V>>::get
             at ./rancor/src/lib.rs:23
  11: zemeroth::core::execute::wound_or_kill
             at src/core/execute.rs:754
  12: zemeroth::core::execute::try_execute_passive_ability_burn
             at src/core/execute.rs:173
  13: zemeroth::core::execute::try_execute_passive_abilities_tick
             at src/core/execute.rs:248
  14: zemeroth::core::execute::try_execute_passive_abilities_on_move
             at src/core/execute.rs:222
  15: zemeroth::core::execute::execute_use_ability
             at src/core/execute.rs:936
  16: zemeroth::core::execute::execute
             at src/core/execute.rs:35
  17: zemeroth::screen::game::Game::do_command_inner
             at src/screen/game.rs:323
  18: zemeroth::screen::game::Game::do_command
             at src/screen/game.rs:330
  19: zemeroth::screen::game::Game::handle_event_click
             at src/screen/game.rs:449
  20: <zemeroth::screen::game::Game as hate::screen::Screen>::handle_event
             at src/screen/game.rs:490
  21: hate::screen_stack::Screens::handle_event
             at hate/src/screen_stack.rs:42
  22: hate::visualizer::Visualizer::handle_events
             at hate/src/visualizer.rs:60
  23: hate::visualizer::Visualizer::tick
             at hate/src/visualizer.rs:49
  24: hate::visualizer::Visualizer::run
             at hate/src/visualizer.rs:35
  25: zemeroth::main
             at src/main.rs:31
  26: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  27: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  28: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  29: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  30: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  31: main
  32: __libc_start_main
  33: _start
```

**Comment by ozkriff** [comment]
Fixed, thanks for reporting :)
