### ISSUE TITLE
Panic during execution of "jump" command with a wounded spearman

### ISSUE THREAD

**Issue by ozkriff** [ozkriff/zemeroth#262]
Can't reproduce it, but here's a release backtrace:

```text
thread 'main' panicked at 'assertion failed: self.state.parts().agent.get_opt(id).is_some()', src/screen/battle.rs:324:9 
stack backtrace: 
  0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace 
            at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49 
  1: std::sys_common::backtrace::print 
            at libstd/sys_common/backtrace.rs:71 
            at libstd/sys_common/backtrace.rs:59 
  2: std::panicking::default_hook::{{closure}} 
            at libstd/panicking.rs:211 
  3: std::panicking::default_hook 
            at libstd/panicking.rs:227 
  4: std::panicking::rust_panic_with_hook 
            at libstd/panicking.rs:463 
  5: std::panicking::begin_panic 
  6: zemeroth::screen::battle::Battle::set_mode 
  7: <zemeroth::screen::battle::Battle as zemeroth::screen::Screen>::click 
  8: zemeroth::screen::Screens::click 
  9: <zemeroth::MainState as ggez::event::EventHandler>::mouse_button_up_event 
 10: ggez::event::run 
 11: zemeroth::main
...
```

**Comment by ozkriff** [comment]
Another panic during execution of "Rage" ability with one health near an imp with reaction attack.

```text
thread 'main' panicked at 'assertion failed: self.state.parts().agent.get_opt(id).is_some()', src/screen/battle.rs:324:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic
   6: zemeroth::screen::battle::Battle::set_mode
   7: <zemeroth::screen::battle::Battle as zemeroth::screen::Screen>::click
   8: zemeroth::screen::Screens::click
   9: <zemeroth::MainState as ggez::event::EventHandler>::mouse_button_up_event
  10: ggez::event::run
  11: zemeroth::main
...
```
