### ISSUE TITLE
Panic: when attempting to use the knockback ability

### ISSUE THREAD

**Issue by StyMaar** [ozkriff/zemeroth#289]
The game panicked when I tried to use the `knockback` ability on a bomb that was located in an area in flames. The hammerman had two opponents (imp and imp_toxic) next to him when he attempted to use his ability.

Here's the stacktrace :
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:347
   6: rust_begin_unwind
             at libstd/panicking.rs:323
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::panicking::panic
             at libcore/panicking.rs:51
   9: zemeroth::core::execute::try_execute_passive_ability_burn
  10: zemeroth::core::execute::try_execute_passive_abilities_tick
  11: zemeroth::core::execute::execute_use_ability
  12: zemeroth::core::execute::execute
  13: zemeroth::screen::game::Game::do_command_inner
  14: <zemeroth::screen::game::Game as hate::screen::Screen>::handle_event
  15: hate::visualizer::Visualizer::run
  16: zemeroth::main
  17: std::rt::lang_start::{{closure}}
  18: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:305
  19: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  20: std::rt::lang_start_internal
             at libstd/panicking.rs:284
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  21: main
  22: __libc_start_main
  23: <unknown>
```

**Comment by ozkriff** [comment]
This one should be fixed in master. I hope.

**Comment by StyMaar** [comment]
It's really easy to reproduce on V4.0.0: you just need to use `knockback` on a bomb in the flames. If that doesn't crash on master, you can close this bug.

**Comment by ozkriff** [comment]
Yep, I believe its fixed now - https://github.com/ozkriff/zemeroth/issues/232
